### ISSUE TITLE
Update link of Latest Meilisearch blog

### ISSUE THREAD

**Issue by shivaylamba** [meilisearch/awesome-meilisearch#3]
The latest blog post on Meilisearch blog is https://blog.meilisearch.com/kicking-off-knowledge-management-at-meilisearch/

But in the README.md, the latest link is [Latest's release blog post](https://blog.meilisearch.com/whats-new-in-v0-23/) - version 0.23 which needs to be updated.

**Comment by shivaylamba** [comment]
@ferdi05 can I take this up?

**Comment by ferdi05** [comment]
absolutely, thanks

**Comment by ferdi05** [comment]
But here you want to link the latest release link
