### ISSUE TITLE
Meilisearch Brand Assets

### ISSUE THREAD

**Issue by fmerian** [meilisearch/awesome-meilisearch#39]
hi there 👋 

would it be possible to add a link to your brand assets?

couldn't find it here or on meilisearch.com. ping @chayaline?

thanks!

**Comment by CaroFG** [comment]
Hello! You can find them in the [devrel repo](https://github.com/meilisearch/devrel/tree/main/assets/logos)

**Comment by fmerian** [comment]
awesome, thanks! do you think it's worth adding a link here?

**Comment by CaroFG** [comment]
Yes, that's a great idea, I'll add a link!
